services:
  app:
    build: .
    container_name: challenge_app_api
    ports: ["8080:8080"]
    env_file: [.env]
    command: /app/api
    depends_on:
      - db
      - nats

  worker:
    build: .
    container_name: challenge_app_worker
    env_file: [.env]
    command: /app/worker
    depends_on:
      - db
      - nats

  nats:
    image: nats:2.10-alpine
    container_name: challenge_nats
    ports: ["4222:4222", "8222:8222"]
    command: "-js"

  db:
    image: postgres:15
    container_name: challenge_db_postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: