global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'telemetry-api'
    static_configs:
      - targets: ['app:8081'] 
  - job_name: 'telemetry-worker'
    static_configs:
      - targets: ['worker:8082'] 